### PR TITLE
Bring morph.io scraperwiki fork up-to-date

### PR DESCRIPTION
**Pull request by andylolz**
[scraperwiki/scraperwiki-python](https://github.com/scraperwiki/scraperwiki-python) is now python3 compatible. This PR brings the openaustralia fork in line with that, while preserving the morph-specific changes to default database and table names.

### CODE REVIEW

**Comment by henare** [comment]
@andylolz are these changes breaking? i.e. if we merge this will everyone's existing Python scrapers break?

**Comment by andylolz** [comment]
V good point, @henare!

Comparing the READMEs, there are no obvious changes. The `options` param has been removed from `scraperwiki.pdftoxml(pdfdata, options='')` but actually [that was a typo anyway](https://github.com/openaustralia/scraperwiki-python/blob/4fc7e2b2/scraperwiki/utils.py#L38).

The move from 0.4.2 to 0.5 _is_ breaking for anyone using `scraperwiki.runlog`. However, `scraperwiki.runlog` doesn’t appear to have been documented, so I’m not sure anyone should be too upset that it has gone.

I’m not sure about the move from 0.3.11 to 0.4.0… I’ll investigate that a bit more!

**Comment by henare** [comment]
It sounds like it would be too dangerous to merge this without doing some broad testing across the scrapers that use it. In the mean time you can point your morph.io scrapers to your fork and get the upgrades immediately :zap:

**Comment by andylolz** [comment]
Yep – I agree. No worries!

**Comment by henare** [comment]
Cool, I'll close this for now. If we decide to do the broad testing in the future we can always reopen it.

**Pull request closed without merging**
